# Generated by Django 3.1.4 on 2020-12-18 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='price',
            new_name='salary',
        ),
    ]
