# Generated by Django 3.1.4 on 2020-12-12 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0004_auto_20201212_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toy',
            name='tags',
            field=models.ManyToManyField(related_name='toys', to='toys.Tag'),
        ),
    ]
