# Generated by Django 3.1.4 on 2020-12-16 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0006_auto_20201214_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='toy',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
